### ISSUE TITLE
 platformio-ide-terminal installation failed - node-pty-prebuilt 0.7.6 

### ISSUE THREAD

**Issue by AugustoPiva** [daviwil/node-pty-prebuilt#20]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version:  0.7.6

## Issue description

When trying to get package platform-ide-terminal on Atom facing the following problem:

> node-pty-prebuilt@0.7.6 install C:\Users\augus\AppData\Local\Temp\apm-install-dir-119624-7144-1c6olho.bvfhl\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js

C:\Users\augus\AppData\Local\Temp\apm-install-dir-119624-7144-1c6olho.bvfhl\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\augus\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\augus\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\augus\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\augus\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\augus\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\augus\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\augus\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\augus\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\augus\AppData\Local\Temp\apm-install-dir-119624-7144-1c6olho.bvfhl\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\augus\AppData\Local\Temp\apm-install-dir-119624-7144-1c6olho.bvfhl\package.json'
npm WARN apm-install-dir-119624-7144-1c6olho.bvfhl No description
npm WARN apm-install-dir-119624-7144-1c6olho.bvfhl No repository field.
npm WARN apm-install-dir-119624-7144-1c6olho.bvfhl No README data
npm WARN apm-install-dir-119624-7144-1c6olho.bvfhl No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\augus\.atom\.apm\_logs\2019-07-24T12_26_42_300Z-debug.log

**Comment by the-j0k3r** [comment]
use https://github.com/bus-stop/terminus

**Comment by uaibo** [comment]
> use https://github.com/bus-stop/terminus

You saved my day, thank you!
