### ISSUE TITLE
Node-pty-prebuilt@0.7.6 install failed during Platformio-ide-terminal installation for Atom

### ISSUE THREAD

**Issue by noemitotos** [daviwil/node-pty-prebuilt#21]
## Environment details

- OS: Mojave
- OS version: 10.14.5
- node-pty version: node-pty-prebuilt@0.7.6

## Issue description
Not able to install Platformio-ide-terminal due to the following error:

Installing “platformio-ide-terminal@2.9.1” failed. 

> node-pty-prebuilt@0.7.6 install /private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/apm-install-dir-119624-4376-796xnv.qtz6e/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/AppTranslocation/4B0C2630-5797-40E9-8162-6F6EA878C7B5/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/AppTranslocation/4B0C2630-5797-40E9-8162-6F6EA878C7B5/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/AppTranslocation/4B0C2630-5797-40E9-8162-6F6EA878C7B5/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd /private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/apm-install-dir-119624-4376-796xnv.qtz6e/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/apm-install-dir-119624-4376-796xnv.qtz6e/package.json'
npm WARN apm-install-dir-119624-4376-796xnv.qtz6e No description
npm WARN apm-install-dir-119624-4376-796xnv.qtz6e No repository field.
npm WARN apm-install-dir-119624-4376-796xnv.qtz6e No README data
npm WARN apm-install-dir-119624-4376-796xnv.qtz6e No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/noemitotos/.atom/.apm/_logs/2019-07-24T14_31_11_828Z-debug.log

**Comment by linjialiang** [comment]
>atom 1.39.1

```shell
C:\Users\emad>apm install platformio-ide-terminal
Installing platformio-ide-terminal to C:\Users\emad\.atom\packages failed

> node-pty-prebuilt@0.7.6 install C:\Users\emad\AppData\Local\Temp\apm-install-dir-119626-13128-l0el9e.xve8\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\emad\AppData\Local\Temp\apm-install-dir-119626-13128-l0el9e.xve8\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\emad\AppData\Local\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\emad\AppData\Local\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\emad\AppData\Local\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\emad\AppData\Local\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\emad\AppData\Local\atom\app-1.39.1\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Users\\emad\\AppData\\Local\\atom\\app-1.39.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\emad\\AppData\\Local\\atom\\app-1.39.1\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\emad\AppData\Local\Temp\apm-install-dir-119626-13128-l0el9e.xve8\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\emad\AppData\Local\Temp\apm-install-dir-119626-13128-l0el9e.xve8\package.json'
npm WARN apm-install-dir-119626-13128-l0el9e.xve8 No description
npm WARN apm-install-dir-119626-13128-l0el9e.xve8 No repository field.
npm WARN apm-install-dir-119626-13128-l0el9e.xve8 No README data
npm WARN apm-install-dir-119626-13128-l0el9e.xve8 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\emad\.atom\.apm\_logs\2019-07-26T02_22_58_255Z-debug.log
```

**Comment by ivankravets** [comment]
@the-j0k3r what to do now? I can't understand why we switched to this package. Could you fork this repository and prepare binaries for all systems? There is a blocked issue https://github.com/platformio/platformio-atom-ide/issues/2233

I think we should revert back PlatformIO IDE Terminal to our pre-built binaries and archive whole repo. So, no new PRs which break terminal.

Thanks!

**Comment by the-j0k3r** [comment]
> I think we should revert back PlatformIO IDE Terminal to our pre-built binaries and archive whole repo. So, no new PRs which break terminal.

I dont think this is a good way to handle this, but you own the repo/project and you made it clear you dont want to keep it going also.

> I can't understand why we switched to this package

We did because no binaries were being built for newer atom, and it is based on a outdated and unmaintained pty,js, we did it because it works better and many bugs were squashed because of the change.
Im not sure if I can prepare binaries for all systems any time soon, I need time we dont have to study the repo and try to get the builds going. Im not a js person either, so this is also an issue.
I am trying though to get some help with that while I learn and see what needs doing.

**Comment by the-j0k3r** [comment]
use https://github.com/bus-stop/terminus problem is gone
