### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by jfrux** [daviwil/node-pty-prebuilt#9]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version: 0.7.6

## Issue description

Have you seen this before?

```
App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\jfrux\Projects\workbench\app\node_modules\node-pty-prebuilt\build\Release\pty.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\jfrux\Projects\workbench\app\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:9:11)
    at Object.<anonymous> (C:\Users\jfrux\Projects\workbench\app\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:167:3)
```

**Comment by daviwil** [comment]
Which version of Electron are you building against?

**Comment by jfrux** [comment]
Your guess is as good as mine…

Jk, actually… so… I feel bad again…
I ran a build and it worked but when I just tried to start it it did no run.
Very sorry! Let’s tuck this one away until it actually is an issue.

**Comment by daviwil** [comment]
Just out of curiosity, can you give me a little more context on where your using `node-pty-prebuilt`?  Is it in an existing Electron application that you're working on?  If so, you should be able to tell the Electron version from your `package.json`, usually in a field called `electronVersion`.

**Comment by jfrux** [comment]
Oh I was partially kidding about not knowing.
I’m definitely certain where to get it, I just was feeling kind of stupid because I think this issue is resolved as well… most likely my newbie project.

https://github.com/openpilot-community/workbench
